site_name: 同济课程评价镜像站
site_description: tongji.icu (同济大学课程评价系统) 的静态镜像站
site_url: https://your-username.github.io/tongji-course-scheduler
site_author: Agent-4

# 仓库信息
repo_name: tongji-course-scheduler
repo_url: https://github.com/your-username/tongji-course-scheduler

# 构建配置
docs_dir: docs
site_dir: site
use_directory_urls: false

# 主题配置
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

# 导航结构
nav:
  - 首页: index.html
  - 课程:
    - 课程列表: pages/courses/index.html
    - 课程搜索: pages/search/index.html
  - 统计: pages/statistics/index.html

# 插件
plugins:
  - search:
      lang: zh
  - minify:
      minify_html: true

# Markdown 扩展
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

# 额外配置
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://1.tongji.icu
      name: 原站点
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # 替换为你的 Google Analytics ID

# 额外 CSS
extra_css:
  - stylesheets/extra.css

# 版权信息
copyright: |
  数据来源: <a href="https://1.tongji.icu" target="_blank">1.tongji.icu</a> |
  本站为镜像站，仅供参考